// resources/js/Pages/Welcome.jsx
export default function Welcome({ name = "Guest" }) {
    return (
        <div className="min-h-screen flex items-center justify-center bg-gray-100 dark:bg-gray-900">
            <div className="max-w-md w-full bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
                <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-4">
                    Welcome to Inertia.js + React!
                </h1>
                <p className="text-gray-600 dark:text-gray-300 mb-4">
                    Hello, {name}! Your Inertia.js setup with React is working
                    correctly.
                </p>
                <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-md p-4">
                    <p className="text-sm text-blue-800 dark:text-blue-200">
                        🎉 You're now ready to build amazing things with Laravel
                        + Inertia.js + React!
                    </p>
                </div>
            </div>
        </div>
    );
}

// resources/js/Pages/Welcome.vue
<script setup lang="ts">
interface Props {
    laravelVersion?: string;
    phpVersion?: string;
}

defineProps<Props>();
</script>

<template>
    <div
        class="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 flex items-center justify-center"
    >
        <div class="text-center">
            <h1 class="text-5xl font-bold text-white mb-4">
                Welcome to Inertia + Vue
            </h1>
            <p class="text-xl text-slate-300 mb-8">
                Your Laravel application is now powered by Vue.js with
                Inertia.js
            </p>
            <div class="flex gap-4 justify-center">
                <a
                    href="https://inertiajs.com"
                    target="_blank"
                    class="px-6 py-3 bg-purple-600 hover:bg-purple-700 text-white rounded-lg font-semibold transition-colors"
                >
                    Inertia Docs
                </a>
                <a
                    href="https://vuejs.org"
                    target="_blank"
                    class="px-6 py-3 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg font-semibold transition-colors"
                >
                    Vue Docs
                </a>
            </div>
            <div v-if="laravelVersion" class="mt-8 text-slate-400 text-sm">
                Laravel v{{ laravelVersion }} (PHP v{{ phpVersion }})
            </div>
        </div>
    </div>
</template>
